const categories = (type) => {
  if (type === "profession")
    return [
      "Doctor",
      "Lawyer",
      "Tailor",
      "Carpenter",
      "Teacher",
      "Trader",
      "Engineer",
      "Electrician",
      "Mechanical Engineer",
      "Politician",
      "Entrepreneur",
      "Founder/CEO",
      "Marketer",
      "Nurse",
      "Sale Manager",
      "Banker",
      "Data Analyst",
      "Actor",
      "Actress",
      "Software Engineer",
      "Pilot",
      "Solder(Army)",
      "Police",
      "Driver",
      "Rider",
      "Footballer",
      "Boxer",
      "Journalist",
      "Accountant",
      "Writer",
      "Health Practitioner",
      "Freelancer",
      "Estate Agent",
      "Car Dealer",
      "Web designer",
      "Broker",
      "Lifeguard",
      "Nail Carrier",
      "Photographer",
      "Bartender",
      "Cleaner",
      "Driver",
      "Statistician",
      "Operator",
      "Technologist",
      "Lecturer",
      "Professor",
      "Surveyor",
      "Dental hygienist",
      "Dietician",
      "Consultant",
      "Artist",
      "Dentist",
      "Librarian",
      "Pharmacist",
      "Farmer",
      "Importer",
      "Exporter",
      "Plumber",
      "Hairdresser",
      "Fashion Designer",
      "Surgeon",
      "Firefighter",
      "Waiter",
      "Chef",
      "Barbarian",
      "Scientist",
      "Designer",
      "Secretary",
      "Mechanic",
      "Electrician",
      "Painter",
      "Architect",
      "Veterinarian",
      "Technician",
      "Software Developer",
      "Instructor",
      "Labourer",
      "Cashier",
      "Actuary",
      "Pastor",
      "Prophet",
      "Alpha Alhaji",
      "Alpha Alhajah",
      "Herbalist",
      "King",
      "Student",
      "Navy",
      "Business Woman",
      "Chief",
      "Comedian",
      "Investor",
      "Philanthropists",
      "Business Man",
    ];

  if (type === "business")
    return [
      "Top Notch Restaurant",
      "Top Notch Boutique",
      "Top Notch Communication Company",
      "Top Notch Fashion Business",
      "Top Notch Beauty Care/Salon",
      "Top Notch Hotel",
      "Top Notch Hospital",
      "News/Media company",
      "Top Notch Entertainment Company",
      "Top Notch Manufacture company",
      "Top Notch Agriculture company",
      "Top Notch Health/Care company",
      "Top Notch Event and Party Service company",
      "Top Notch Electrical Accessories Company",
      "Top Notch Education service",
      "Top Notch Private School",
      "Top Notch Logistics/Package Company",
      "Top Notch Computer/ICT/Programing company",
      "Top Notch Training company",
      "Top Notch production company",
      "Top Notch Wholesales company",
      "Top Notch Retails company",
      "Top Notch Art Service company",
      "Top Notch investment company",
      "Top Notch Financial Company",
      "Top Notch Micro Finance",
      "Top Notch Pharmacy",
      "Top Notch Marketing/advertising",
      "Top Notch printing and publishing company",
      "Top Notch Industrial Service company",
      "Top Notch Transport services",
      "Top Notch Travels & Tour Company",
      "Top Notch Auto/Dealer Company",
      "Top Notch Bar/Lounge/Club",
      "Top Notch Guardians /Counseling",
      "Top Notch Importation Company",
      "Top Notch Exportation Company",
      "Top Notch Legal Company",
      "Top Notch Agent Company",
      "Top Notch Musical Brand",
      "Top Recruitment Company",
      "Top Notch Business Center/Cyber Cafe",
    ];

  return [];
};

export default categories;
